### ISSUE TITLE
raptorjs.org shows GoDaddy parked domain page

### ISSUE THREAD

**Issue by rmg** [raptorjs/raptorjs.github.com#1]
Going to the project's site, http://raptorjs.org, shows a GoDaddy parked domain landing page instead of the website. Since this repo's CNAME is pointing at the custom domain it also redirects to that landing page.

**Comment by patrick-steele-idem** [comment]
Thanks for letting me know @rmg. The "RaptorJS" brand is now defunct and the website itself is not very useful. Many of the individual "raptor" modules still live on `npm` and are useful, but they are not being promoted. I went ahead and deleted the CNAME so that visiting http://raptorjs.github.io/ works.
